version: "3.9"
services:
  web:
    build: typescript/simple-mercari-web
    ports:
      - "3000:3000"
    volumes:
      - .:/web_code
    environment:
      - API_URL=http://localhost:9000/
  app:
    build:
      context: .
      dockerfile: python/dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/app_code
    environment:
      - FRONT_URL=http:/localhost:3000/
