# syntax=docker/dockerfile:1

FROM python:3

WORKDIR /app

COPY python python
RUN pip3 install -r python/requirements.txt

COPY db db

WORKDIR python

CMD [ "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "9000" ]