# syntax=docker/dockerfile:1

FROM python:3

WORKDIR /app

COPY python/requirements.txt python/requirements.txt
RUN pip3 install -r python/requirements.txt

COPY . .

WORKDIR python

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000" ]